# Generated by Django 6.0.4 on 2026-04-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='price',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='General medicine', max_length=100),
            preserve_default=False,
        ),
    ]
